//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hack2019PO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hack2019PO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Voľby&quot;: &quot;Voľby do Európskeho parlamentu 2019&quot;,
        ///    &quot;Mesto&quot;: &quot;Prešov&quot;,
        ///    &quot;Ulica&quot;: &quot;Bajkalská&quot;,
        ///    &quot;Or._č.&quot;: &quot;   1      &quot;,
        ///    &quot;Adresa&quot;: &quot;Bajkalská 4859/1&quot;,
        ///    &quot;Názov_okrsku&quot;: &quot;Základná škola, Bajkalská 29&quot;,
        ///    &quot;Číslo_okrsku&quot;: &quot;1&quot;,
        ///    &quot;Volebná_miestnosť&quot;: &quot;Základná škola, Bajkalská&quot;,
        ///    &quot;Adresa_volebnej_miestnosti&quot;: &quot;Bajkalská 4865/29&quot;,
        ///    &quot;Zapisovateľ&quot;: &quot;Ing. arch. Helena Jacová&quot;,
        ///    &quot;Názov_volebného_obvodu&quot;: &quot;Volebný obvod pre voľby prezidenta SR 2019 - 1. kolo&quot;,
        ///    &quot;Mestsk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zoznam {
            get {
                return ResourceManager.GetString("Zoznam", resourceCulture);
            }
        }
    }
}
